---
title: "Key Takeaways from posit::conf(2023)"
subtitle: "An awesome conference of diverse topics and professional expertise."
description-meta: ""
date: "9-21-2023"
date-modified: today
description: "This year, I was fortunate to attend the 2023 Posit Conference. Though my schedule only allowed for virtual attendence, I was excited to chat with new people and learn about data science. In this post, I outline the main insights that I took away from this event."
categories:
  - conference
image: img-001.svg
draft: true
---

## New Conference, New Perspectives

Prior to a couple years ago, I would have never seen myself attending a data science conference. I was a lowly field biologist, not a programmer, so what would I get from it? Now that I was able to experience a Posit Conference, I have a response, A LOT! This event served as a great introduction to the professional community of open source data science.

Though my participation was limited to virtual means, I garnered a significant amount of knowledge and, potentially more importantly, a different perspective. As a result, I thought it would be beneficial to consolidate these insights in a blog post, primarily to streamline my own thoughts but also to share them with a wider audience.

**The following items are some of my core insights from this conference.**

### Data Scientists Are Everywhere

I'm not sure why, but my biased brain imagined a room full of dull data nerds, mostly of the same professional background, as the typical scene at a data science conference. This couldn't be further from the truth at this conference (except maybe the nerdy part).

The diversity of backgrounds, expertise, and workplace at posit::conf(2023) was mind-blowing. There were people from healthcare, mathematics departments, biological research centers, computer and data science industries, engineering firms, and a suite of environmental organizations. Even more awesome was the (continuation of) Birds of a Feather special interest groups where folks of similar workflows and topics could meet to chat. 

### Quarto Is the Future

One of my greatest topical highlights from the conference was learning more about Quarto. I had recently switched several of my projects over to Quarto in hopes that this new format would catch on. Boy did it! I think I watched almost every presentation focusing on its capabilities. Everything from websites to academic writing.

I have used R Markdown documents for several years now. Mostly for technical reporting and workflow documentation. Jupyter Notebooks were also spread across my work, but .R and .Rmd files for sure dominated. I was excited to see how the flexibility of Quarto could streamline more of my work.

### Interactivity Is Key

In the era of dashboards, I could imagine most data scientists are familiar with the importance of interactive ways of viewing data. Proficiency in Shiny app development has always been on my to-do list.

### Design With Time In Mind

As a self-prescribed continuous theme-changer, I can appreciate the dedication to boundary setting when it comes to design.

## My Favorite Talks

While I enjoyed every talk I was able to listen in on, there were several that stood out to me personally. This list is influenced mostly by my current areas of growth, especially using Quarto and other tools for academic use. My work does not involve package development nor much cloud computing, so I wasn't able to glean much on that front.


## Closing Remarks

I would like to end this post by thanking Posit for hosting this wonderful conference and for opening the virtual attendance option up to academics free of charge (*grad students silently rejoice*). It was a great experience and I hope to join in-person in the future.

