---
title: "About Me"
abstract: I work as a wildlife ecologist and geospatial practitioner to find solutions for researching and conserving our natural resources.
abstract-title: ""
---

## My Interests

My professional interests are at the intersection of geospatial and ecological science, particularly projects using GIS to inform conservation efforts.

:::: {.columns}

::: {.column width="50%"}

- Applied Conservation Science
- Spatial and Movement Ecology
- Imperiled Species Conservation

:::

::: {.column width="50%"}

- Landscape Connectivity & Planning
- Web and Cartographic Design
- Open Source Programming

:::

::::

## My Highlights

In my 7+ years of progressive experience in conservation, geospatial, and environmental science, I have acquired a diverse range of expertise across multiple disciplines, which includes the following competencies.

- Demonstrated experience with desktop, web, and mobile GIS software.

- Working knowledge of R to perform statistical analyses, data wrangling, and data visualization.

- Front-end web development experience using HTML and CSS coding languages.

- Proficient in managing large datasets using standardized software and methods.

- Skillful in cartographic design using open source and proprietary mapping applications.

- Adept at using R Markdown and Quarto for reproducible reporting.



## Education

### Formal Learning

My formal education is in wildlife conservation science and geographic information systems.

- **M.A., Geography** | University of Missouri-Columbia | Expect. May 2025

- **B.S., Wildlife Ecology** | University of Wisconsin-Stevens Point | May 2019

My college coursework expanded into several adjacent topics (e.g., soil science, watershed management, statistics, and forestry) which allows my work to be interdisciplinary.
 
### Continued Learning

I pride myself on being someone who seeks out continuous learning. Be it at my work or during my free time, I love learning new techniques, workflows, and software.

- **Esri MOOC** (Massive Open Online Courses), including Spatial Data Science and Cartography.

- **LinkedIn Learning**, including a variety of modules on data science, coding in R, and creating maps programmatically.

## Work Experience

### Post-Degree

Since obtaining my degree, I have held a variety of roles within the conservation career space.

- **Assistant Wildlife Diversity Coordinator** | MO Department of Conservation | 08/22--Present

- **Assistant Natural History Biologist** | MO Department of Conservation | 10/19--08/22

- **Biological Science Technician** | Agassiz NWR, U.S. Fish and Wildlife Service | 05/19--10/19

### Pre-Degree

While in college, I gained high-quality research and management experience.

- **Ungulate Ecology Student Teaching Assistant** | UWSP | 01/19--05/19

- **Student Project Assistant** | Wisconsin Center for Wildlife | 12/17--05/19

## Professional Organizations

### The Wildlife Society

The Wildlife Society (TWS) has been my primary professional organization since my freshman year of college. I have held several leadership roles within TWS during this time.

### Society for Conservation GIS

The Society for Conservation GIS (SCGIS) is a relatively new addition to my professional involvement. I am excited to learn new ways to volunteer with this wonderful organization.

## How To Contact Me

Interested in working on a project together or wondering if I still have the code for a past project?

Please contact me via [email](mailto:benjamin.tjepkes+websitecontact@gmail.com) or through my [LinkedIn profile](https://www.linkedin.com/in/benjamintjepkes/) with any inquiries.

